version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_PUBLIC_URL: jdbc:mysql://root:PCDygquNNTVHqGAYDhGRynwkGKtEAfYM@hopper.proxy.rlwy.net:28322/railway
      MYSQLUSER: root
      MYSQL_ROOT_PASSWORD: PCDygquNNTVHqGAYDhGRynwkGKtEAfYM
      MYSQLDATABASE: railway
      MYSQLPORT: 3306
      MYSQLHOST: mysql.railway.internal

    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  eureka-server:
    build: eureka-server/
    image: matias7132/eureka-server:latest
    ports:
      - 8761:8761

  config-server:
    build: config-server/
    image: matias7132/config-server:latest
    ports:
      - 8889:8889
    depends_on:
      - eureka-server

  gateway:
    build: gateway/
    image: matias7132/gateway:latest
    ports:
      - 8085:8085
    depends_on:
      - eureka-server
      - config-server

  user-service:
    build: user-service/
    image: matias7132/user-service:latest
    ports:
      - 8087:8087
    environment:
      DB_URL: jdbc:mysql://root:PCDygquNNTVHqGAYDhGRynwkGKtEAfYM@hopper.proxy.rlwy.net:28322/railway
      DB_USERNAME: root
      DB_PASSWORD: PCDygquNNTVHqGAYDhGRynwkGKtEAfYM
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started

  accounts-service:
    build: accounts-service/
    image: matias7132/accounts-service:latest
    ports:
      - 8084:8084
    environment:
      DB_URL: jdbc:mysql://root:PCDygquNNTVHqGAYDhGRynwkGKtEAfYM@hopper.proxy.rlwy.net:28322/railway
      DB_USERNAME: root
      DB_PASSWORD: PCDygquNNTVHqGAYDhGRynwkGKtEAfYM
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started

  api-activity:
    build: api-activity/
    image: matias7132/api-activity:latest
    ports:
      - 9091:9091
    environment:
      DB_URL: jdbc:mysql://root:PCDygquNNTVHqGAYDhGRynwkGKtEAfYM@hopper.proxy.rlwy.net:28322/railway
      DB_USERNAME: root
      DB_PASSWORD: PCDygquNNTVHqGAYDhGRynwkGKtEAfYM
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started

  api-transfers:
    build: api-transfers/
    image: matias7132/api-transfers:latest
    ports:
      - 9092:9092
    environment:
      DB_URL: jdbc:mysql://root:PCDygquNNTVHqGAYDhGRynwkGKtEAfYM@hopper.proxy.rlwy.net:28322/railway
      DB_USERNAME: root
      DB_PASSWORD: PCDygquNNTVHqGAYDhGRynwkGKtEAfYM
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started

  api-cards:
    build: api-cards/
    image: matias7132/api-cards:latest
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:mysql://root:PCDygquNNTVHqGAYDhGRynwkGKtEAfYM@hopper.proxy.rlwy.net:28322/railway
      DB_USERNAME: root
      DB_PASSWORD: PCDygquNNTVHqGAYDhGRynwkGKtEAfYM
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started

volumes:
  mysql-data:
