spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://backend-billetera-digital-1.onrender.com # Config Service en Render
      discovery:
        serviceId: config-service
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000, https://front-end-vercel-sable.vercel.app/login" # Agrega la URL del frontend en producción
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: https://backend-billetera-digital.onrender.com
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: https://backend-billetera-digital-4.onrender.com
          predicates:
            - Path=/accounts/**
        - id: api-cards
          uri: https://backend-billetera-digital-6.onrender.com
          predicates:
            - Path=/accounts/{accountId}/cards/**
        - id: api-activity
          uri: https://backend-billetera-digital-5.onrender.com
          predicates:
            - Path=/accounts/{accountId}/activity/**
        - id: api-transfers
          uri: https://backend-billetera-digital-7.onrender.com
          predicates:
            - Path=/accounts/{accountId}/transferences/**

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/info
  client:
    serviceUrl:
      defaultZone: https://backend-billetera-digital-2.onrender.com/eureka/

server:
  port: 8085 # Solo para entorno local, en Render no es necesario

main:
  allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        cloud:
          gateway: DEBUG
        security: DEBUG


